part: RS0302
datasheet:
  lang: en
  source: local-reference
  file: C:\Users\OoiJianHong\Downloads\Reference\Reference\RS0302_(RevA.4.1).pdf
  extract: C:\Users\OoiJianHong\Eugene's Repo\PythonAutomation\ate\config\datasheets\text\rs0302.txt
specs: []
